### ISSUE TITLE
/scan /report_pretty is not working

### ISSUE THREAD

**Issue by raghulk15** [Qualys/spring4scanwin#2]
When I try to pass the argument as "/scan /report_pretty" for this scanner utility, it is not generating any scan summary logs. However, it is working for other aruguments.

**Comment by MouseFortune** [comment]
You can fix this by downloading the latest version of the new code (not the exe).

Download the ZIP and extract the code (from GitHub)
Install Visual Studio 2015
Open the "Spring4Scanner.vcxproj" in Visual Studio
Press Build
The built exe can be found in "\spring4scanwin-master\spring4scanwin-master\build\x64\Debug\output\Spring4Scan.exe"

**Comment by romw** [comment]
Should now be fixed.

See: https://github.com/Qualys/spring4scanwin/releases/tag/1.0.2
